server:
  port: 8080

# 企查查
qichacha:
  appkey: 82c1901c0b8711ea89b97cd30aeb1e8c
  seckey: E569IGHQYAAADQ7M5LBKIL4K9ADRDDEO
  apiurl: https://pro.qichacha.com/api/yj/ECIMatch/CompanyVerify

user:
  password: 123456

spring:
  # 数据源
  datasource:
    username: root
    password: 479803313
    url: jdbc:mysql://127.0.0.1:3306/sx?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

  # 热重启
  devtools:
    restart:
      enabled: true

  # 允许同名bean覆盖注册
  main:
    allow-bean-definition-overriding: true

jodconverter:
  enabled: true
  # open office 安装路径
  office-home: C:\Program Files (x86)\OpenOffice 4
  max-tasks-per-process: 10
  port-numbers: 8100
  kill-existing-process: true

